version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    environment:
      MOCHA_FILE: '../reports/mocha.xml'
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "package-lock.json" }}
      - run:
          name: Installing npm dependencies
          command: npm install
      - run:
          name: Resetting package-lock changes
          command: git checkout -- package-lock.json
      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Preparing lockfile update
          command: $(npm bin)/greenkeeper-lockfile-update

      # Code Quality checks
      # TODO: Lint commit message
      # with git log --format=%B -n 1 $CIRCLE_SHA1 | npx commitlint

      # Build
      - run:
          name: Transpiling source code
          command: npm run -s compile
      - run:
          name: Building docs
          command: npm run -s docs

      # Test
      - run:
          name: Linting source files
          command: npm run -s lint -- --format junit --output-file ~/reports/eslint.xml
          when: always

      - run:
          name: Running tests
          command: NODE_ENV=test npx nyc npm test -- --reporter mocha-circleci-reporter
          when: always

      - run:
          name: Checking docs for broken links
          command: npm run -s test:docs
          when: always

      - run:
          name: Checking test coverage
          command: npx nyc check-coverage --statements 90 --branches 90 --functions 90 --lines 90
          when: always

      # Store Results
      - run:
          name: Reporting test coverage
          command: npx nyc report --reporter=lcov > ~/reports/coverage.lcov | node_modules/.bin/codecov
      - store_test_results:
          path: ~/reports
          when: always
      - store_artifacts:
          path: ~/reports
          when: always

      # Deployment
      - add_ssh_keys
      - deploy:
          name: Updating lockfile
          command: $(npm bin)/greenkeeper-lockfile-upload
      - deploy:
          name: Deploy changes
          command: |
            echo "$NPM_TOKEN" > ~/.npmrc

            git config --global user.email circleci@circleci && git config --global user.name CircleCI && git remote --v

            npx bump-version release --release-files out docs/api --gh-token $GITHUB_TOKEN --verbose
